#Activer ou non la vérification des permissions lorsqu'une commande est exécutée
enable-permissions: false

#Activer ou non le support des .mcfunction personnalisées (à partir de la 1.12)
enable-mcfunction-support: false

Application:
  #Activer/Désactiver la possibilté de connection depuis un Fk config.
  Enabled: true
  #Si vous louez votre serveur, certains ports sont dédiés aux plugins, mais il faudra peut-être le réserver
  Port: 50000
  #Il est très fortement conseillé de changer de mot de passe.
  Password: "pass"